owner: wgyt
repo: stats.wgyt.tk

sites:
  - name: bot.wgyt.tk
    url: https://bot.wgyt.tk/
  - name: www.wgyt.tk
    url: https://www.wgyt.tk/
  - name: wgyt.tk
    url: https://wgyt.tk/
  - name: wgytcraft.cf
    url: https://wgytcraft.cf/
    # todo: move these to a new status page:
  - name: www.meower.tk
    url: https://www.meower.tk/
  - name: meower.tk
    url: https://meower.tk/
  - name: meowerplus.tk
    url: https://meowerplus.tk/
  - name: galacticaos.tk
    url: https://galacticaos.tk/
assignees:
  - wgyt

status-website:
  theme: night
  name: Wgyt Status
  logoUrl: https://avatars.githubusercontent.com/u/68466727?s=600&v=4
  cname: stats.wgyt.tk # Custom CNAME
commitMessages:
  commitAuthorName: "wgytbot"
  commitAuthorEmail: "83586655+wgytbot@users.noreply.github.com"
